spring:
  datasource:
    username: springstudent
    url: jdbc:mysql://localhost:3306/notes_app
    password: springstudent
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: 8081

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'